# Generated by Django 3.2.4 on 2024-07-15 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.RenameField(
            model_name='carrito',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='carrito',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.AddField(
            model_name='elementocarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementos', to='biblioteca.carrito'),
        ),
        migrations.AddField(
            model_name='elementocarrito',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.servicio'),
        ),
    ]
